<?php
$config = array('area' => array(array(
                                	'field'=>'nombrearea',
                                	'label'=>'nombrearea',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'descripcionarea',
                                	'label'=>'descripcionarea',
                                	'rules'=>'required|trim|xss_clean'
                                ))
                ,
                'documentos' => array(array(
                                    'field'=>'tipotramite_id',
                                    'label'=>'tipotramite_id',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'nombredocumento',
                                    'label'=>'nombredocumento',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'descripciondocumento',
                                    'label'=>'descripciondocumento',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'estado',
                                    'label'=>'estado',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'dniremitente',
                                    'label'=>'dniremitente',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'emailremitente',
                                    'label'=>'emailremitente',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'apellidopaternoremitente',
                                    'label'=>'apellidopaternoremitente',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'apellidomaternoremitente',
                                    'label'=>'apellidomaternoremitente',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                               array(
                                    'field'=>'nombresremitente',
                                    'label'=>'nombresremitente',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fechaingreso',
                                    'label'=>'fechaingreso',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fechafin',
                                    'label'=>'fechafin',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'observaciones',
                                    'label'=>'observaciones',
                                    'rules'=>'trim|xss_clean'
                                )
                                ,
                                array(
                                    'field'=>'archivodocumento',
                                    'label'=>'archivodocumento',
                                    'rules'=>'trim|xss_clean'
                                ))
                ,
                'tipotramite' => array(array(
                                    'field'=>'nombretipotramite',
                                    'label'=>'nombretipotramite',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'descripciontipotramite',
                                    'label'=>'descripciontipotramite',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'imagen',
                                    'label'=>'imagen',
                                    'rules'=>'trim|xss_clean'
                                ))
                ,
                'usuarios' => array(array(
                                    'field'=>'nombres',
                                    'label'=>'Nombres',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'dni',
                                    'label'=>'DNI',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'apellidopaterno',
                                    'label'=>'apellidopaterno',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'apellidomaterno',
                                    'label'=>'apellidomaterno',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'cargo',
                                    'label'=>'cargo',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fotoperfil',
                                    'label'=>'fotoperfil',
                                    'rules'=>'trim|xss_clean'
                                ),
                                
                                array(
                                    'field'=>'estado',
                                    'label'=>'Estado',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'email',
                                    'label'=>'Email',
                                    'rules'=>'required|trim|valid_email|xss_clean'
                                ),
                                array(
                                    'field'=>'contrasenha',
                                    'label'=>'contrasenha',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'telefono',
                                    'label'=>'telefono',
                                    'rules'=>'required|trim|xss_clean'
                                )
                                ,
                                array(
                                    'field'=>'celular',
                                    'label'=>'celular',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'idarea',
                                    'label'=>'idarea',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'permisos_id',
                                    'label'=>'permisos_id',
                                    'rules'=>'required|trim|xss_clean'
                                ))
                ,      
                'iteraciondocumento' => array(array(

                                    'field' => 'iddocumento',
                                    'label' => 'iddocumento',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'dniaprobacion',
                                    'label'=>'dniaprobacion',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'idareaactual',
                                    'label'=>'idareaactual',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'idareasiguiente',
                                    'label'=>'idareasiguiente',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fechaaprobacion',
                                    'label'=>'fechaaprobacion',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'observaciones',
                                    'label'=>'observaciones',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fechaingreso',
                                    'label'=>'areaactual',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'estadotramite',
                                    'label'=>'estadotramite',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'permiso',
                                    'label'=>'permiso',
                                    'rules'=>'trim|xss_clean|required'
                                ))
                ,
                'secuenciatramite' => array(array(

                                    'field' => 'codsecuenciatramite',
                                    'label' => 'codsecuenciatramite',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'nombresecuencia',
                                    'label'=>'nombresecuencia',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'tipotramite_id',
                                    'label'=>'tipotramite_id',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'codsecuenciaprevia',
                                    'label'=>'codsecuenciaprevia',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'estadoaccionsecuencia',
                                    'label'=>'estadoaccionsecuencia',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'idarea',
                                    'label'=>'idarea',
                                    'rules'=>'trim|xss_clean'
                                ))
		);
			   